### ISSUE TITLE
Error in commit references unknown v${version}.tar.gz

### ISSUE THREAD

**Issue by mwbringmann** [power-ras/libservicelog#1]
Error in recent commit produces the following error message for rpmbuild:

[root@RHEL8 libservicelog]# rpmbuild -ba ~/rpmbuild/SPECS/libservicelog.spec
error: Bad source: /root/rpmbuild/SOURCES/v1.1.18.tar.gz: No such file or directory
[root@RHEL8 libservicelog]#

The commit includes the change,

-Source0: https://github.com/power-ras/libservicelog.git
+Source0: https://github.com/power-ras/%{name}/archive/v%{version}.tar.gz

which should have been,

-Source0: https://github.com/power-ras/libservicelog.git
+Source0: https://github.com/power-ras/%{name}/archive/libservicelog-%{version}.tar.gz

to match the file generated by the 'make dist-gzip' operation.

**Comment by hegdevasant** [comment]
Thanks for the report. I will fix it next week.

-Vasant
